DATA SEGMENT
    ARR DW 0FFFFH,08B8BH,0AAAAH,2222H,04C4CH
    LEN EQU 05H
DATA ENDS

CODE SEGMENT
    ASSUME CS: CODE, DS: DATA

START:

    MOV AX,DATA
    MOV DS,AX
    
    MOV CH,LEN
    
BACK2: MOV CL, LEN
       LEA SI,ARR
BACK1: MOV AX,[SI]
       MOV BX,[SI+2]
       CMP AX,BX
       JNC SKIP
       JZ SKIP
       MOV [SI+2],AX
       MOV [SI],BX
SKIP:  INC SI
       INC SI
       DEC CL
       JNZ BACK1
       DEC CH
       JNZ BACK2

MOV AH,4CH
INT 21H

CODE ENDS
END START